classdef ADCParameters < handle & matlab.mixin.CustomDisplay
    %% =============================================
    %% CONTAINER OF META OBJECTS FOR ADC PARAMETERS
    %% ==============================================
    properties (SetAccess = private)
        Params struct
    end

    methods
        %% ==================================================
        %% Constructor of the Meta Objects For ADC Parameters
        %% ==================================================
        function obj = ADCParameters()
            Schema = obj.GetSchema();
            obj.Params = struct();

            for k = 1:numel(Schema)
                S = Schema{k}; 

                if isfield(S, 'Unit') && ~isempty(S.Unit) && ...
                    ~ismissing(S.Unit) && S.Unit ~= ""
                    obj.Params.(S.Key) = ADCMeta( ...
                        S.Name, ...
                        S.Validator, ...
                        S.DataType, ...
                        S.Unit);
                else
                    obj.Params.(S.Key) = ADCMeta( ...
                        S.Name, ...
                        S.Validator, ...
                        S.DataType);
                end
            end

            % Default AGC gain limits preserve the general low-frequency
            % configuration. Design-specific configurations can override
            % these values without changing the AGC implementation.
            obj.setValue("MinAGCGain", 0.1);
            obj.setValue("MaxAGCGain", 10.0);
            obj.setValue("InitialAGCGain", 1.0);
        end
        %% Retrieves The Stored Value Of A Parameter Using Its Key
        function value = getValue(obj,key)

            key = char(key);

            if ~isfield(obj.Params,key)
                error('Parameters:UnknownKey', ...
                    'Parameter "%s" does not exist.', key);
            end

            value = obj.Params.(key).Value;
        end
        
        %% Assigns A New Value To A Parameter Using Its Key
        function setValue(obj,key,val)

            key = char(key);

            if ~isfield(obj.Params,key)
                error('Parameters:UnknownKey', ...
                    'Parameter "%s" does not exist.', key);
            end

            obj.Params.(key).Value = val;
        end
        %% Retrieves The Metadata Associated With A Parameter Key
        function metaObj = getADCMeta(obj,key)

            key = char(key);

            if ~isfield(obj.Params,key)
                error('Parameters:UnknownKey', ...
                    'Parameter "%s" does not exist.', key);
            end

            metaObj = obj.Params.(key);
        end
   
        %% User Input Request
        function PromptUser(obj)
            names = fieldnames(obj.Params);
            for k = 1:numel(names)
                param = obj.Params.(names{k});
                while true
                    try
                        if isprop(param, 'Unit') && ...
                            ~ismissing(param.Unit) && param.Unit ~= ""
                            promptStr = sprintf("Enter %s (%s): ", ...
                                param.Name, param.Unit);
                        else
                            promptStr = sprintf("Enter %s: ", param.Name);
                        end
                        
                        value = input(promptStr);
                        param.Value = value;
                        break
                    catch ME
                        fprintf(2, "Error: %s\n", ME.message);
                    end
                end
            end
        end
    end

    %% =============================================
    %% CUSTOM DISPLAY PATTERNS IN THE COMMAND WINDOW
    %% =============================================
    methods (Access = protected)
        function displayScalarObject(obj)
            %% Print the default class header line
            header = getHeader(obj);
            disp(header);
            
            %% Extract keys and preallocate data arrays for table display
            keys = fieldnames(obj.Params);
            nParams = numel(keys);
            
            Names = strings(nParams, 1);
            Values = zeros(nParams, 1); 
            DataTypes = strings(nParams, 1);
            Units = strings(nParams, 1);
            
            for k = 1:nParams
                metaObj = obj.Params.(keys{k});
                Names(k) = metaObj.Name;
                Values(k) = double(metaObj.Value);     
                DataTypes(k) = metaObj.DataType;
                
                %% Safely Parse Unassigned Or Empty Strings
                if ismissing(metaObj.Unit) || metaObj.Unit == ""
                    Units(k) = "-";
                else
                    Units(k) = metaObj.Unit;
                end
            end
            
            %% Readable Overview Table
            T = table(Names, Values, DataTypes, Units, 'RowNames', keys);
            T.Properties.VariableNames = {'Parameter Name', 'Value', ...
                'Data Type', 'Unit'};
            
           %% Display the Table Block Directly Into the Command Line Window
            disp(T);
        end
    end   
    
    %% Parameters Configuration
    methods (Static, Access = private)
        function Schema = GetSchema()
            Schema = {
                struct( ...
                'Key', "Fs", ...
                'Name', "Oversampling Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FData", ...
                'Name', "Data Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FData2", ...
                'Name', "Second Data Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "Fnoise", ...
                'Name', "Out-of-Band Noise Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FcLow", ...
                'Name', "Low Cutoff Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FcHigh", ...
                'Name', "High Cutoff Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )


                %% HPF Design Specifications Used For Characterization
                struct( ...
                'Key', "FstopHPF", ...
                'Name', "HPF Stopband Edge Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FpassHPF", ...
                'Name', "HPF Passband Edge Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "ApassHPF", ...
                'Name', "HPF Maximum Passband Loss", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "AstopHPF", ...
                'Name', "HPF Minimum Stopband Attenuation", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "DCRejectionHPF", ...
                'Name', "HPF Minimum Measured DC Rejection", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "MaxSettlingTimeHPF", ...
                'Name', "HPF Maximum DC-Step Settling Time", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "SettlingToleranceHPF", ...
                'Name', "HPF DC-Step Settling Tolerance", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', '>', 0, '<', 1}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "MaxDesiredToneLossHPF", ...
                'Name', "HPF Maximum Desired-Tone Loss", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                %% LPF Design Specifications Used For Characterization
                struct( ...
                'Key', "FpassLPF", ...
                'Name', "LPF Passband Edge Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "FstopLPF", ...
                'Name', "LPF Stopband Edge Frequency", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Hz" ...
                )

                struct( ...
                'Key', "ApassLPF", ...
                'Name', "LPF Maximum Passband Loss", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "AstopLPF", ...
                'Name', "LPF Minimum Stopband Attenuation", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "MinInterferenceAttenuationLPF", ...
                'Name', "LPF Minimum Interference Attenuation", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "MaxDesiredToneLossLPF", ...
                'Name', "LPF Maximum Desired-Tone Loss", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "MaxSettlingTimeLPF", ...
                'Name', "LPF Maximum Step Settling Time", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "SettlingToleranceLPF", ...
                'Name', "LPF Step Settling Tolerance", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', '>', 0, '<', 1}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "MaxStepOvershootLPF", ...
                'Name', "LPF Maximum Step Overshoot", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', '>=', 0, '<', 1}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "DC", ...
                'Name', "DC Amplitude", ...
                'Validator', @mustBeNumeric, ...
                'DataType', "double", ...
                'Unit', "Volts" ...
                )

                struct( ...
                'Key', "DF", ...
                'Name', "Downsampling Factor", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "Vfs", ...
                'Name', "Quantizer Full-Scale Voltage Range", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "MinAGCGain", ...
                'Name', "Minimum AGC Linear Gain", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', 'positive'}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "MaxAGCGain", ...
                'Name', "Maximum AGC Linear Gain", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', 'positive'}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "InitialAGCGain", ...
                'Name', "Initial AGC Linear Gain", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', 'positive'}), ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "NoiseGateThreshold", ...
                'Name', "Noise-Gate Input-Envelope Threshold", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', 'nonnegative'}), ...
                'DataType', "double", ...
                'Unit', "Volts" ...
                )

                struct( ...
                'Key', "MinAGCTargetOccupancy", ...
                'Name', "Minimum AGC Target-Window Occupancy", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', '>', 0, '<=', 100}), ...
                'DataType', "double", ...
                'Unit', "Percent" ...
                )

                struct( ...
                'Key', "MaxAGCClippingPercentage", ...
                'Name', "Maximum AGC Output Clipping Percentage", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'real', 'finite', '>=', 0, '<=', 100}), ...
                'DataType', "double", ...
                'Unit', "Percent" ...
                )

                struct( ...
                'Key', "MaxAGCAttackTime", ...
                'Name', "Maximum AGC Attack Response Time", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "MaxAGCReleaseTime", ...
                'Name', "Maximum AGC Release Response Time", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "MaxAGCSNRDegradation", ...
                'Name', "Maximum AGC SNR Degradation", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "MaxAGCSINRDegradation", ...
                'Name', "Maximum AGC SINR Degradation", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "dB" ...
                )

                struct( ...
                'Key', "GainRelease", ...
                'Name', "Gain Release Time Constant", ...
                'Validator',  @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "GainAttack", ...
                'Name', "Gain Attack Time Constant", ...
                'Validator',  @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "Dur", ...
                'Name', "Signal Duration", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "FrameLength", ...
                'Name', "Frame Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, {'positive', 'integer', 'finite'}), ...
                'DataType', "double", ...
                'Unit', "Samples" ...
                )

                struct( ...
                'Key', "Ad", ...
                'Name', "Data Signal Amplitude", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Volts" ...
                )

                struct( ...
                'Key', "Ad2", ...
                'Name', "Second Data Signal Amplitude", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Volts" ...
                )

                struct( ...
                'Key', "An", ...
                'Name', "Out-of-Band Noise Signal Amplitude", ...
                'Validator', @mustBePositive, ...
                'DataType', "double", ...
                'Unit', "Volts" ...
                )
                
                struct( ...
                'Key', "Lambda", ...
                'Name', "Exponential Decay Constant", ...
                'Validator', @mustBeNumeric, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "Sigma", ...
                'Name', "Gaussian Pulse Standard Deviation", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "mu", ...
                'Name', "Gaussian Pulse Mean Or Peak Location", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "EnvRelease", ...
                'Name', "Smoothing Filter Release Time Constant", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )
                
                struct( ...
                'Key', "EnvAttack", ...
                'Name', "Smoothing Filter Attack Time Constant", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "GateRelease", ...
                'Name', "Noise Gate Release Time Constant", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "GateAttack", ...
                'Name', "Noise Gate Attack`Time Constant", ...
                'Validator', @mustBeNonnegative, ...
                'DataType', "double", ...
                'Unit', "Seconds" ...
                )

                struct( ...
                'Key', "Aburst", ...
                'Name', "Gaussian Pulse Amplitude", ...
                'Validator', @mustBeNumeric, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "EST", ...
                'Name', "Exponential Decay Start Time", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "Anf", ...
                'Name', "AWGN Noise Floor Amplitude", ...
                'Validator', @mustBeNumeric, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "nLpf", ...
                'Name', "Filter Order LPF", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                )
                
                struct( ...
                'Key', "nHpf", ...
                'Name', "Filter Order HPF", ...
                'Validator', @mustBePositive, ...
                'DataType', "double" ...
                ) 

                struct( ...
                'Key', "NumBits", ...
                'Name', "Quantizer Number of Bits", ...
                'Validator', @mustBeInteger, ...
                'DataType', "double" ...
                ) 

                struct( ...
                'Key', "N", ...
                'Name', "FFT Length", ...
                'Validator', @mustBeInteger, ...
                'DataType', "double" ...
                )

                struct( ...
                'Key', "STFTWindowLength", ...
                'Name', "STFT Window Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'integer', 'finite', '>=', 2}), ...
                'DataType', "double", ...
                'Unit', "Samples" ...
                )

                struct( ...
                'Key', "STFTOverlapLength", ...
                'Name', "STFT Overlap Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'nonnegative', 'integer', 'finite'}), ...
                'DataType', "double", ...
                'Unit', "Samples" ...
                )

                struct( ...
                'Key', "STFTFFTLength", ...
                'Name', "STFT FFT Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'positive', 'integer', 'finite'}), ...
                'DataType', "double", ...
                'Unit', "Points" ...
                )

                struct( ...
                'Key', "PSDWindowLength", ...
                'Name', "Welch PSD Window Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'integer', 'finite', '>=', 2}), ...
                'DataType', "double", ...
                'Unit', "Samples" ...
                )

                struct( ...
                'Key', "PSDOverlapLength", ...
                'Name', "Welch PSD Overlap Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'nonnegative', 'integer', 'finite'}), ...
                'DataType', "double", ...
                'Unit', "Samples" ...
                )

                struct( ...
                'Key', "PSDFFTLength", ...
                'Name', "Welch PSD FFT Length", ...
                'Validator', @(x) validateattributes( ...
                    x, {'numeric'}, ...
                    {'scalar', 'positive', 'integer', 'finite'}), ...
                'DataType', "double", ...
                'Unit', "Points" ...
                )
            };
        end
    end
end
