classdef TestADCEncoderIntegration < matlab.unittest.TestCase
    %% =====================================================
    %% ADC-OWNED END-TO-END ENCODER INTEGRATION TEST
    %% =====================================================
    % Verifies the complete ADC repository boundary:
    %
    %   SignalGenerator -> HPF -> LPF -> AGC -> Sampler
    %   -> Bipolar Midtread Quantizer -> ADCEncoder
    %
    
    methods (Test)

        function testSignalChainThroughADCEncoderIntegration(testCase)
            %% Compares frame processing with one whole-vector reference

            P = testCase.createSignalChainParameters();
            DF = P.getValue("DF");
            NumBits = P.getValue("NumBits");

            OldRngState = rng;
            CleanupObj = onCleanup(@() rng(OldRngState)); 
            rng(53, "twister");

            %% Frame-Based ADC-Owned Chain

            SG = SignalGenerator(P);
            FrameFilter = ADCFilter(P);
            FrameAGC = AGC(P);
            FrameADC = ADC(P);
            FrameEncoder = ADCEncoder(P);

            CompleteInput = zeros(0, 1);
            CompleteHPFOutput = zeros(0, 1);
            CompleteLPFOutput = zeros(0, 1);
            CompleteAGCOutput = zeros(0, 1);
            CompleteSampledOutput = zeros(0, 1);
            CompleteSampleIndex = zeros(0, 1);
            CompleteQuantizedOutput = zeros(0, 1);
            CompleteQuantizerIndices = zeros(0, 1);
            CompleteQuantizationError = zeros(0, 1);
            CompleteOffsetBinary = zeros(0, 1, 'uint8');
            CompleteTwosComplement = zeros(0, 1, 'int8');

            ADCSamplingFrequency = NaN;
            NumberFrames = 0;

            while ~SG.IsDone()
                InputFrame = SG.GenNoisySignal();

                HPFOutputFrame = ...
                    FrameFilter.ProcessHPFFrame(InputFrame);
                LPFOutputFrame = ...
                    FrameFilter.ProcessLPFFrame(HPFOutputFrame);
                AGCOutputFrame = ...
                    FrameAGC.GainControl(LPFOutputFrame);

                [SampledOutputFrame, SampleIndexFrame, FrameFrequency] = ...
                    FrameADC.Sampler(AGCOutputFrame);

                [QuantizedOutputFrame, QuantizerIndexFrame, ...
                    QuantizationErrorFrame] = ...
                    FrameADC.Midtread(SampledOutputFrame);

                [OffsetBinaryFrame, TwosComplementFrame] = ...
                    FrameEncoder.Encode(QuantizerIndexFrame);

                CompleteInput = ...
                    [CompleteInput; InputFrame]; %#ok<AGROW>
                CompleteHPFOutput = ...
                    [CompleteHPFOutput; HPFOutputFrame]; %#ok<AGROW>
                CompleteLPFOutput = ...
                    [CompleteLPFOutput; LPFOutputFrame]; %#ok<AGROW>
                CompleteAGCOutput = ...
                    [CompleteAGCOutput; AGCOutputFrame]; %#ok<AGROW>
                CompleteSampledOutput = ...
                    [CompleteSampledOutput; SampledOutputFrame]; %#ok<AGROW>
                CompleteSampleIndex = ...
                    [CompleteSampleIndex; SampleIndexFrame]; %#ok<AGROW>
                CompleteQuantizedOutput = ...
                    [CompleteQuantizedOutput; ...
                     QuantizedOutputFrame]; %#ok<AGROW>
                CompleteQuantizerIndices = ...
                    [CompleteQuantizerIndices; ...
                     QuantizerIndexFrame]; %#ok<AGROW>
                CompleteQuantizationError = ...
                    [CompleteQuantizationError; ...
                     QuantizationErrorFrame]; %#ok<AGROW>
                CompleteOffsetBinary = ...
                    [CompleteOffsetBinary; OffsetBinaryFrame(:)]; %#ok<AGROW>
                CompleteTwosComplement = ...
                    [CompleteTwosComplement; ...
                     TwosComplementFrame(:)]; %#ok<AGROW>

                if isnan(ADCSamplingFrequency)
                    ADCSamplingFrequency = FrameFrequency;
                else
                    testCase.verifyEqual( ...
                        FrameFrequency, ADCSamplingFrequency);
                end

                NumberFrames = NumberFrames + 1;
            end

            %% Whole-Vector Reference

            WholeFilter = ADCFilter(P);
            ExpectedHPFOutput = ...
                WholeFilter.ProcessHPFFrame(CompleteInput);
            ExpectedLPFOutput = ...
                WholeFilter.ProcessLPFFrame(ExpectedHPFOutput);

            WholeAGC = AGC(P);
            ExpectedAGCOutput = ...
                WholeAGC.GainControl(ExpectedLPFOutput);

            ExpectedSampleIndex = ...
                (0:DF:numel(ExpectedAGCOutput)-1)';
            ExpectedSampledOutput = ...
                ExpectedAGCOutput(ExpectedSampleIndex + 1);

            ReferenceADC = ADC(P);
            [ExpectedQuantizedOutput, ExpectedQuantizerIndices, ...
                ExpectedQuantizationError] = ...
                ReferenceADC.Midtread(ExpectedSampledOutput);

            ReferenceEncoder = ADCEncoder(P);
            [ExpectedOffsetBinary, ExpectedTwosComplement] = ...
                ReferenceEncoder.Encode(ExpectedQuantizerIndices);

            [ActualOffsetBits, ActualTwosBits] = ...
                FrameEncoder.Binary( ...
                CompleteOffsetBinary, CompleteTwosComplement);
            [ExpectedOffsetBits, ExpectedTwosBits] = ...
                ReferenceEncoder.Binary( ...
                ExpectedOffsetBinary, ExpectedTwosComplement);

            %% Verify Every ADC-Owned Hand-off

            testCase.verifyEqual( ...
                CompleteHPFOutput, ExpectedHPFOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteLPFOutput, ExpectedLPFOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteAGCOutput, ExpectedAGCOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteSampledOutput, ExpectedSampledOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteSampleIndex, ExpectedSampleIndex);
            testCase.verifyEqual( ...
                CompleteQuantizedOutput, ExpectedQuantizedOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteQuantizerIndices, ExpectedQuantizerIndices);
            testCase.verifyEqual( ...
                CompleteQuantizationError, ...
                ExpectedQuantizationError, "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteOffsetBinary, ExpectedOffsetBinary);
            testCase.verifyEqual( ...
                CompleteTwosComplement, ExpectedTwosComplement);

            %% Verify Numerical and Logical Encoder Representations

            testCase.verifyClass(CompleteOffsetBinary, 'uint8');
            testCase.verifyClass(CompleteTwosComplement, 'int8');
            testCase.verifySize( ...
                CompleteOffsetBinary, ...
                [numel(ExpectedQuantizerIndices), 1]);
            testCase.verifySize( ...
                CompleteTwosComplement, ...
                [numel(ExpectedQuantizerIndices), 1]);

            testCase.verifyEqual( ...
                double(CompleteOffsetBinary), ...
                CompleteQuantizerIndices);
            testCase.verifyEqual( ...
                int64(CompleteTwosComplement), ...
                int64(CompleteQuantizerIndices) - ...
                bitshift(int64(1), NumBits - 1));

            testCase.verifyEqual( ...
                ActualOffsetBits, ExpectedOffsetBits);
            testCase.verifyEqual( ...
                ActualTwosBits, ExpectedTwosBits);
            testCase.verifySize( ...
                ActualOffsetBits, ...
                [numel(ExpectedQuantizerIndices), NumBits]);
            testCase.verifySize( ...
                ActualTwosBits, ...
                [numel(ExpectedQuantizerIndices), NumBits]);

            %% Verify Quantization and Streaming 

            testCase.verifyEqual( ...
                CompleteQuantizationError, ...
                CompleteQuantizedOutput - CompleteSampledOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                ADCSamplingFrequency, P.getValue("Fs") / DF);
            testCase.verifyEqual( ...
                FrameAGC.SamplesProcessed, numel(CompleteInput));
            testCase.verifyEqual( ...
                FrameAGC.FramesProcessed, NumberFrames);
            testCase.verifyEqual( ...
                FrameADC.InputSamplesProcessed, numel(CompleteInput));
            testCase.verifyEqual( ...
                FrameADC.OutputSamplesProduced, ...
                numel(ExpectedSampledOutput));
            testCase.verifyEqual( ...
                FrameADC.FramesProcessed, NumberFrames);
            testCase.verifyEqual( ...
                FrameFilter.HPFState, WholeFilter.HPFState, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameFilter.LPFState, WholeFilter.LPFState, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.Envelope, WholeAGC.Envelope, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.Gain, WholeAGC.Gain, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.GateGain, WholeAGC.GateGain, ...
                "AbsTol", 1e-12);
            testCase.verifyTrue(SG.IsDone());
        end
    end

    methods (Access = private)

        function P = createSignalChainParameters(~)
            %% Parameters for the ADC-Owned Chain Through Encoding

            P = ADCParameters();

            % 100 high-rate samples in four irregular 31-sample frames.
            P.setValue("Fs", 20000);
            P.setValue("FrameLength", 31);
            P.setValue("Dur", 0.005);
            P.setValue("DF", 4);

            % Signal generator.
            P.setValue("Aburst", 0.5);
            P.setValue("mu", 0.0015);
            P.setValue("Sigma", 0.0005);
            P.setValue("Ad", 1.0);
            P.setValue("Lambda", 300);
            P.setValue("EST", 0.003);
            P.setValue("FData", 500);
            P.setValue("An", 0.1);
            P.setValue("Fnoise", 7000);
            P.setValue("Anf", 1e-3);
            P.setValue("DC", 0.25);

            % HPF and anti-alias LPF.
            P.setValue("FcHigh", 20);
            P.setValue("FcLow", 2000);
            P.setValue("nHpf", 4);
            P.setValue("nLpf", 6);

            % AGC and eight-bit bipolar ADC.
            P.setValue("Vfs", 1.0);
            P.setValue("NumBits", 8);
            P.setValue("EnvAttack", 0.005);
            P.setValue("EnvRelease", 0.020);
            P.setValue("GainAttack", 0.005);
            P.setValue("GainRelease", 0.020);
            P.setValue("GateAttack", 0.005);
            P.setValue("GateRelease", 0.020);
        end
    end
end
