name: MATLAB Automated Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  execute-runner:
    name: Run Custom MATLAB Runner
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      # Runs your test runner file directly from the repository root
      - name: Run test runner script
        uses: matlab-actions/run-command@v2
        with:
          command: run('ADCRunTests.m')
